export const GET_TOP_RATED_PLACE_REQUEST = 'GET_TOP_RATED_PLACE_REQUEST';
export const GET_TOP_RATED_PLACE_SUCCESS = 'GET_TOP_RATED_PLACE_SUCCESS';
export const GET_TOP_RATED_PLACE_FAIL = 'GET_TOP_RATED_PLACE_FAIL';
export const GET_TOP_RATED_PLACE_RESET = 'GET_TOP_RATED_PLACE_RESET';
