export const GET_NOTIFICATIONS_FOR_USER_REQUEST =
  'GET_NOTIFICATIONS_FOR_USER_REQUEST';
export const GET_NOTIFICATIONS_FOR_USER_SUCCESS =
  'GET_NOTIFICATIONS_FOR_USER_SUCCESS';
export const GET_NOTIFICATIONS_FOR_USER_FAIL =
  'GET_NOTIFICATIONS_FOR_USER_FAIL';
export const GET_NOTIFICATIONS_FOR_USER_RESET =
  'GET_NOTIFICATIONS_FOR_USER_RESET';

export const CREATE_NOTIFICATION_REQUEST = 'CREATE_NOTIFICATION_REQUEST';
export const CREATE_NOTIFICATION_SUCCESS = 'CREATE_NOTIFICATION_SUCCESS';
export const CREATE_NOTIFICATION_FAIL = 'CREATE_NOTIFICATION_FAIL';
export const CREATE_NOTIFICATION_RESET = 'CREATE_NOTIFICATION_RESET';
