export const GET_NOTIFICATIONS_FOR_USER_REQUEST =
  'GET_NOTIFICATIONS_FOR_USER_REQUEST';
export const GET_NOTIFICATIONS_FOR_USER_SUCCESS =
  'GET_NOTIFICATIONS_FOR_USER_SUCCESS';
export const GET_NOTIFICATIONS_FOR_USER_FAIL =
  'GET_NOTIFICATIONS_FOR_USER_FAIL';
export const GET_NOTIFICATIONS_FOR_USER_RESET =
  'GET_NOTIFICATIONS_FOR_USER_RESET';

export const CREATE_NOTIFICATION_REQUEST = 'CREATE_NOTIFICATION_REQUEST';
export const CREATE_NOTIFICATION_SUCCESS = 'CREATE_NOTIFICATION_SUCCESS';
export const CREATE_NOTIFICATION_FAIL = 'CREATE_NOTIFICATION_FAIL';
export const CREATE_NOTIFICATION_RESET = 'CREATE_NOTIFICATION_RESET';

export const SET_NOTIFICATION_AS_READ_REQUEST =
  'SET_NOTIFICATION_AS_READ_REQUEST';
export const SET_NOTIFICATION_AS_READ_SUCCESS =
  'SET_NOTIFICATION_AS_READ_SUCCESS';
export const SET_NOTIFICATION_AS_READ_FAIL = 'SET_NOTIFICATION_AS_READ_FAIL';
export const SET_NOTIFICATION_AS_READ_RESET = 'SET_NOTIFICATION_AS_READ_RESET';
