export const GET_NOTIFICATIONS_FOR_USER_REQUEST =
  'GET_NOTIFICATIONS_FOR_USER_REQUEST';
export const GET_NOTIFICATIONS_FOR_USER_SUCCESS =
  'GET_NOTIFICATIONS_FOR_USER_SUCCESS';
export const GET_NOTIFICATIONS_FOR_USER_FAIL =
  'GET_NOTIFICATIONS_FOR_USER_FAIL';
export const GET_NOTIFICATIONS_FOR_USER_RESET =
  'GET_NOTIFICATIONS_FOR_USER_RESET';
