export const GET_ALL_PLACES_REQUEST = 'GET_ALL_PLACES_REQUEST';
export const GET_ALL_PLACES_SUCCESS = 'GET_ALL_PLACES_SUCCESS';
export const GET_ALL_PLACES_FAIL = 'GET_ALL_PLACES_FAIL';
export const GET_ALL_PLACES_RESET = 'GET_ALL_PLACES_RESET';

export const GET_NEARBY_PLACES_REQUEST = 'GET_NEARBY_PLACES_REQUEST';
export const GET_NEARBY_PLACES_SUCCESS = 'GET_NEARBY_PLACES_SUCCESS';
export const GET_NEARBY_PLACES_FAIL = 'GET_NEARBY_PLACES_FAIL';
export const GET_NEARBY_PLACES_RESET = 'GET_NEARBY_PLACES_RESET';

export const GET_PLACES_BY_CATAGORY_REQUEST = 'GET_PLACES_BY_CATAGORY_REQUEST';
export const GET_PLACES_BY_CATAGORY_SUCCESS = 'GET_PLACES_BY_CATAGORY_SUCCESS';
export const GET_PLACES_BY_CATAGORY_FAIL = 'GET_PLACES_BY_CATAGORY_FAIL';
export const GET_PLACES_BY_CATAGORY_RESET = 'GET_PLACES_BY_CATAGORY_RESET';

export const CREATE_PLACE_REQUEST = 'CREATE_PLACE_REQUEST';
export const CREATE_PLACE_SUCCESS = 'CREATE_PLACE_SUCCESS';
export const CREATE_PLACE_FAIL = 'CREATE_PLACE_FAIL';
export const CREATE_PLACE_RESET = 'CREATE_PLACE_RESET';

export const GET_PLACES_BY_USER_REQUEST = 'GET_PLACES_BY_USER_REQUEST';
export const GET_PLACES_BY_USER_SUCCESS = 'GET_PLACES_BY_USER_SUCCESS';
export const GET_PLACES_BY_USER_FAIL = 'GET_PLACES_BY_USER_FAIL';
export const GET_PLACES_BY_USER_RESET = 'GET_PLACES_BY_USER_RESET';
