export const GET_ALL_PLACES_REQUEST = 'GET_ALL_PLACES_REQUEST';
export const GET_ALL_PLACES_SUCCESS = 'GET_ALL_PLACES_SUCCESS';
export const GET_ALL_PLACES_FAIL = 'GET_ALL_PLACES_FAIL';
export const GET_ALL_PLACES_RESET = 'GET_ALL_PLACES_RESET';
