export const GET_REVIEWS_BY_PLACE_REQUEST = 'GET_REVIEWS_BY_PLACE_REQUEST';
export const GET_REVIEWS_BY_PLACE_SUCCESS = 'GET_REVIEWS_BY_PLACE_SUCCESS';
export const GET_REVIEWS_BY_PLACE_FAIL = 'GET_REVIEWS_BY_PLACE_FAIL';
export const GET_REVIEWS_BY_PLACE_RESET = 'GET_REVIEWS_BY_PLACE_RESET';

export const GET_REVIEWS_BY_USER_REQUEST = 'GET_REVIEWS_BY_USER_REQUEST';
export const GET_REVIEWS_BY_USER_SUCCESS = 'GET_REVIEWS_BY_USER_SUCCESS';
export const GET_REVIEWS_BY_USER_FAIL = 'GET_REVIEWS_BY_USER_FAIL';
export const GET_REVIEWS_BY_USER_RESET = 'GET_REVIEWS_BY_USER_RESET';

export const GET_REVIEW_BY_ID_REQUEST = 'GET_REVIEW_BY_ID_REQUEST';
export const GET_REVIEW_BY_ID_SUCCESS = 'GET_REVIEW_BY_ID_SUCCESS';
export const GET_REVIEW_BY_ID_FAIL = 'GET_REVIEW_BY_ID_FAIL';
export const GET_REVIEW_BY_ID_RESET = 'GET_REVIEW_BY_ID_RESET';

export const GET_FAVORITE_REVIEWS_REQUEST = 'GET_FAVORITE_REVIEWS_REQUEST';
export const GET_FAVORITE_REVIEWS_SUCCESS = 'GET_FAVORITE_REVIEWS_SUCCESS';
export const GET_FAVORITE_REVIEWS_FAIL = 'GET_FAVORITE_REVIEWS_FAIL';
export const GET_FAVORITE_REVIEWS_RESET = 'GET_FAVORITE_REVIEWS_RESET';

export const CREATE_REVIEW_FOR_PLACE_REQUEST =
  'CREATE_REVIEW_FOR_PLACE_REQUEST';
export const CREATE_REVIEW_FOR_PLACE_SUCCESS =
  'CREATE_REVIEW_FOR_PLACE_SUCCESS';
export const CREATE_REVIEW_FOR_PLACE_FAIL = 'CREATE_REVIEW_FOR_PLACE_FAIL';
export const CREATE_REVIEW_FOR_PLACE_RESET = 'CREATE_REVIEW_FOR_PLACE_RESET';

export const DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST';
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS';
export const DELETE_REVIEW_FAIL = 'DELETE_REVIEW_FAIL';
export const DELETE_REVIEW_RESET = 'DELETE_REVIEW_RESET';

export const LIKE_REQUEST = 'LIKE_REQUEST';
export const LIKE_SUCCESS = 'LIKE_SUCCESS';
export const LIKE_FAIL = 'LIKE_FAIL';
export const LIKE_RESET = 'LIKE_RESET';

export const DISLIKE_REQUEST = 'DISLIKE_REQUEST';
export const DISLIKE_SUCCESS = 'DISLIKE_SUCCESS';
export const DISLIKE_FAIL = 'DISLIKE_FAIL';
export const DISLIKE_RESET = 'DISLIKE_RESET';
