export const GET_REVIEWS_BY_PLACE_REQUEST = 'GET_REVIEWS_BY_PLACE_REQUEST';
export const GET_REVIEWS_BY_PLACE_SUCCESS = 'GET_REVIEWS_BY_PLACE_SUCCESS';
export const GET_REVIEWS_BY_PLACE_FAIL = 'GET_REVIEWS_BY_PLACE_FAIL';
export const GET_REVIEWS_BY_PLACE_RESET = 'GET_REVIEWS_BY_PLACE_RESET';

export const CREATE_REVIEW_FOR_PLACE_REQUEST =
  'CREATE_REVIEW_FOR_PLACE_REQUEST';
export const CREATE_REVIEW_FOR_PLACE_SUCCESS =
  'CREATE_REVIEW_FOR_PLACE_SUCCESS';
export const CREATE_REVIEW_FOR_PLACE_FAIL = 'CREATE_REVIEW_FOR_PLACE_FAIL';
export const CREATE_REVIEW_FOR_PLACE_RESET = 'CREATE_REVIEW_FOR_PLACE_RESET';
