export const GET_REVIEWS_BY_PLACE_REQUEST = 'GET_REVIEWS_BY_PLACE_REQUEST';
export const GET_REVIEWS_BY_PLACE_SUCCESS = 'GET_REVIEWS_BY_PLACE_SUCCESS';
export const GET_REVIEWS_BY_PLACE_FAIL = 'GET_REVIEWS_BY_PLACE_FAIL';
export const GET_REVIEWS_BY_PLACE_RESET = 'GET_REVIEWS_BY_PLACE_RESET';
